### ISSUE TITLE
Switch to `time`

### ISSUE THREAD

**Issue by griffi-gh** [AlephAlpha/build-time#1]
`chrono` depends on an old version of `time` which has multiple security issues and hasn't been updated for an entire year

**Comment by AlephAlpha** [comment]
Thanks for letting me know about that.

It seems that the security issue of `chrono` is caused by getting the local time in multi-threaded program: https://github.com/chronotope/chrono/issues/499. This means that my `build_time_local` macro might be unsound. `time` had a similar issue (https://github.com/time-rs/time/issues/293), and its solution is returning an error unless the program is single-threaded.

I don't know how to work around this. Should I simply remove the `build_time_local` macro?

**Comment by AlephAlpha** [comment]
Maybe I should just wait until `chrono` merge https://github.com/chronotope/chrono/pull/677.

**Comment by AlephAlpha** [comment]
[`chrono 4.20` is finally released](https://github.com/chronotope/chrono/releases/tag/v0.4.20), and the security issue is fixed. I will close this.
